In [6]:
#dependencies
import requests
import json
import datetime
import numpy as np
import pandas as pd
import os
from config import w_api_key

In [7]:
#create empty dataframe
column_names = ['postal_code',
 'country',
 'timestamp',
 'cldCvrMin',
 'cldCvrAvg',
 'cldCvrMax',
 'dewPtMin',
 'dewPtAvg',
 'dewPtMax',
 'feelsLikeMin',
 'feelsLikeAvg',
 'feelsLikeMax',
 'heatIndexMin',
 'heatIndexAvg',
 'heatIndexMax',
 'mslPresMin',
 'mslPresAvg',
 'mslPresMax',
 'precip',
 'presTendMin',
 'presTendAvg',
 'presTendMax',
 'radSolarMin',
 'radSolarAvg',
 'radSolarMax',
 'radSolarTot',
 'relHumMin',
 'relHumAvg',
 'relHumMax',
 'sfcPresMin',
 'sfcPresAvg',
 'sfcPresMax',
 'snowDepth',
 'snowfall',
 'spcHumMin',
 'spcHumAvg',
 'spcHumMax',
 'tempMin',
 'tempAvg',
 'tempMax',
 'windChillMin',
 'windChillAvg',
 'windChillMax',
 'windDirAvg',
 'windDir80mAvg',
 'windDir100mAvg',
 'windSpdMin',
 'windSpdAvg',
 'windSpdMax',
 'windSpd80mMin',
 'windSpd80mAvg',
 'windSpd80mMax',
 'windSpd100mMin',
 'windSpd100mAvg',
 'windSpd100mMax',
 'wetBulbMin',
 'wetBulbAvg',
 'wetBulbMax']
#sanity check
#range_months = pd.date_range(start='1-1-2015',end='7-1-2015',freq='1M')
#for day in range_months:
#    day_start = (day).strftime('%Y-%m-%d')
#    day_end = (day+1*day.freq).strftime('%Y-%m-%d')
#    print(f'working on date: {day}')
#    print(f'{day_start}')
#    print('-')
#    print({day_end})
    #date = str(day)
    #dummy_month = (range_months[date]).strftime('%Y-%m-%d')
    #print(dummy_month)

Empty DataFrame
Columns: [postal_code, country, timestamp, cldCvrMin, cldCvrAvg, cldCvrMax, dewPtMin, dewPtAvg, dewPtMax, feelsLikeMin, feelsLikeAvg, feelsLikeMax, heatIndexMin, heatIndexAvg, heatIndexMax, mslPresMin, mslPresAvg, mslPresMax, precip, presTendMin, presTendAvg, presTendMax, radSolarMin, radSolarAvg, radSolarMax, radSolarTot, relHumMin, relHumAvg, relHumMax, sfcPresMin, sfcPresAvg, sfcPresMax, snowDepth, snowfall, spcHumMin, spcHumAvg, spcHumMax, tempMin, tempAvg, tempMax, windChillMin, windChillAvg, windChillMax, windDirAvg, windDir80mAvg, windDir100mAvg, windSpdMin, windSpdAvg, windSpdMax, windSpd80mMin, windSpd80mAvg, windSpd80mMax, windSpd100mMin, windSpd100mAvg, windSpd100mMax, wetBulbMin, wetBulbAvg, wetBulbMax]
Index: []

[0 rows x 58 columns]

In [28]:
#create variables for the api url
country = 'US'
postal_code = '10019'
#define the API pull function
def pull(start,end):
    base_df = pd.DataFrame(columns = column_names)
#set the start and end dates for months in the form of a list
    range_months = pd.date_range(start,end,freq='1M')

    #not needed anymore, incorporated in the loop
    #dummy variables to change format to match api url data
    #dummy_months = (range_months).strftime('%Y-%m-%d')
    #dummy_months_end = (range_months+1*range_months.freq).strftime('%Y-%m-%d')

    #for each day from x/x/20xx-x/x/20xx ...
    for day in range_months:
        day_start = (day).strftime('%Y-%m-%d')
        day_end = (day+1*day.freq).strftime('%Y-%m-%d')
        try:
        #make the api call
            r = requests.get(f'https://api.weathersource.com/v1/{w_api_key}/postal_codes/{postal_code},{country}/history.json?period=day&timestamp_between={day_start}T00:00,{day_end}T00:00')
            read = r.json()
            print(f'timestamp_between={day_start}T00:00,{day_end}T00:00,length is:{len(read)}')
            #create dummy to temporarily store the dataframe
            dummy_df = pd.DataFrame(read,index=np.arange(start=0,stop=len(read)))
            base_df = base_df.append(dummy_df,ignore_index=False)
        except KeyError:
            print('Error, nothing found, moving to next')
    return base_df

In [34]:
w_1_15_10_15 = pull('01-01-2015','09-30-2015')

timestamp_between=2015-01-31T00:00,2015-02-28T00:00,length is:29
timestamp_between=2015-02-28T00:00,2015-03-31T00:00,length is:32
timestamp_between=2015-03-31T00:00,2015-04-30T00:00,length is:31
timestamp_between=2015-04-30T00:00,2015-05-31T00:00,length is:32
timestamp_between=2015-05-31T00:00,2015-06-30T00:00,length is:31
timestamp_between=2015-06-30T00:00,2015-07-31T00:00,length is:32
timestamp_between=2015-07-31T00:00,2015-08-31T00:00,length is:32
timestamp_between=2015-08-31T00:00,2015-09-30T00:00,length is:31
timestamp_between=2015-09-30T00:00,2015-10-31T00:00,length is:32

In [35]:
#weather has to be called in 10month intervals, as there is a pull limit
w_11_15_8_16 = pull('11-01-2015','08-30-2016')

timestamp_between=2015-11-30T00:00,2015-12-31T00:00,length is:32
timestamp_between=2015-12-31T00:00,2016-01-31T00:00,length is:32
timestamp_between=2016-01-31T00:00,2016-02-29T00:00,length is:30
timestamp_between=2016-02-29T00:00,2016-03-31T00:00,length is:32
timestamp_between=2016-03-31T00:00,2016-04-30T00:00,length is:31
timestamp_between=2016-04-30T00:00,2016-05-31T00:00,length is:32
timestamp_between=2016-05-31T00:00,2016-06-30T00:00,length is:31
timestamp_between=2016-06-30T00:00,2016-07-31T00:00,length is:32
timestamp_between=2016-07-31T00:00,2016-08-31T00:00,length is:32

In [37]:
w_9_16_6_17 = pull('09-01-2016','06-30-2017')

timestamp_between=2016-09-30T00:00,2016-10-31T00:00,length is:32
timestamp_between=2016-10-31T00:00,2016-11-30T00:00,length is:31
timestamp_between=2016-11-30T00:00,2016-12-31T00:00,length is:32
timestamp_between=2016-12-31T00:00,2017-01-31T00:00,length is:32
timestamp_between=2017-01-31T00:00,2017-02-28T00:00,length is:29
timestamp_between=2017-02-28T00:00,2017-03-31T00:00,length is:32
timestamp_between=2017-03-31T00:00,2017-04-30T00:00,length is:31
timestamp_between=2017-04-30T00:00,2017-05-31T00:00,length is:32
timestamp_between=2017-05-31T00:00,2017-06-30T00:00,length is:31
timestamp_between=2017-06-30T00:00,2017-07-31T00:00,length is:32

In [49]:
w_8_17_7_18 = pull('08-01-2017','05-30-2018')

timestamp_between=2017-08-31T00:00,2017-09-30T00:00,length is:31
timestamp_between=2017-09-30T00:00,2017-10-31T00:00,length is:32
timestamp_between=2017-10-31T00:00,2017-11-30T00:00,length is:31
timestamp_between=2017-11-30T00:00,2017-12-31T00:00,length is:32
timestamp_between=2017-12-31T00:00,2018-01-31T00:00,length is:32
timestamp_between=2018-01-31T00:00,2018-02-28T00:00,length is:29
timestamp_between=2018-02-28T00:00,2018-03-31T00:00,length is:32
timestamp_between=2018-03-31T00:00,2018-04-30T00:00,length is:31
timestamp_between=2018-04-30T00:00,2018-05-31T00:00,length is:32

In [50]:
w_6_18_3_19 = pull('06-01-2018','03-30-2019')

timestamp_between=2018-06-30T00:00,2018-07-31T00:00,length is:32
timestamp_between=2018-07-31T00:00,2018-08-31T00:00,length is:32
timestamp_between=2018-08-31T00:00,2018-09-30T00:00,length is:31
timestamp_between=2018-09-30T00:00,2018-10-31T00:00,length is:32
timestamp_between=2018-10-31T00:00,2018-11-30T00:00,length is:31
timestamp_between=2018-11-30T00:00,2018-12-31T00:00,length is:32
timestamp_between=2018-12-31T00:00,2019-01-31T00:00,length is:32
timestamp_between=2019-01-31T00:00,2019-02-28T00:00,length is:29
timestamp_between=2019-02-28T00:00,2019-03-31T00:00,length is:32

In [51]:
w_4_19_1_20 = pull('04-01-2019','01-30-2020')

timestamp_between=2019-04-30T00:00,2019-05-31T00:00,length is:32
timestamp_between=2019-05-31T00:00,2019-06-30T00:00,length is:31
timestamp_between=2019-06-30T00:00,2019-07-31T00:00,length is:32
timestamp_between=2019-07-31T00:00,2019-08-31T00:00,length is:32
timestamp_between=2019-08-31T00:00,2019-09-30T00:00,length is:31
timestamp_between=2019-09-30T00:00,2019-10-31T00:00,length is:32
timestamp_between=2019-10-31T00:00,2019-11-30T00:00,length is:31
timestamp_between=2019-11-30T00:00,2019-12-31T00:00,length is:32
timestamp_between=2019-12-31T00:00,2020-01-31T00:00,length is:32

In [52]:
w_2_20_7_20 = pull('02-01-2020','07-25-2020')

timestamp_between=2020-02-29T00:00,2020-03-31T00:00,length is:32
timestamp_between=2020-03-31T00:00,2020-04-30T00:00,length is:31
timestamp_between=2020-04-30T00:00,2020-05-31T00:00,length is:32
timestamp_between=2020-05-31T00:00,2020-06-30T00:00,length is:31
timestamp_between=2020-06-30T00:00,2020-07-31T00:00,length is:26

In [65]:
#combine dataframes
weather_df = pd.DataFrame(columns = column_names)
weather_df = weather_df.append([w_2_20_7_20, w_4_19_1_20,w_6_18_3_19,w_8_17_7_18,w_9_16_6_17,w_11_15_8_16,w_1_15_10_15],ignore_index=True)
weather_df

,postal_code,country,timestamp,cldCvrMin,cldCvrAvg,cldCvrMax,dewPtMin,dewPtAvg,dewPtMax,feelsLikeMin,...,windSpdMax,windSpd80mMin,windSpd80mAvg,windSpd80mMax,windSpd100mMin,windSpd100mAvg,windSpd100mMax,wetBulbMin,wetBulbAvg,wetBulbMax
0,10019,US,2020-02-29T00:00:00-05:00,0,1,4,8.1,10.9,16.1,13.7,...,16.4,11.5,16.9,22.5,12.7,17.0,22.1,21.5,25.7,29.3
1,10019,US,2020-03-01T00:00:00-05:00,0,0,0,10.9,15.4,21.2,14.9,...,13.3,5.2,12.1,16.5,6.2,12.3,16.9,21.2,29.2,36.3
2,10019,US,2020-03-02T00:00:00-05:00,0,23,100,21.6,32.5,39.9,31.6,...,10.0,8.3,14.4,22.0,9.3,15.0,21.5,30.8,41.6,47.9
3,10019,US,2020-03-03T00:00:00-05:00,1,58,100,41.2,45.8,50.1,45.1,...,11.9,3.0,12.6,20.5,3.3,12.6,21.9,46.2,48.8,52.1
4,10019,US,2020-03-04T00:00:00-05:00,0,1,19,23.6,31.0,38.0,38.7,...,17.9,11.3,20.4,26.6,12.1,20.1,25.8,40.1,42.8,45.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877,10019,US,2015-10-27T00:00:00-04:00,27,70,98,34.0,40.3,44.7,41.1,...,6.1,5.5,8.9,15.2,5.6,9.2,16.0,40.0,45.8,50.0
1878,10019,US,2015-10-28T00:00:00-04:00,53,95,100,45.3,57.0,66.4,49.9,...,18.2,15.2,22.2,32.0,16.1,23.2,32.9,48.4,58.1,66.7
1879,10019,US,2015-10-29T00:00:00-04:00,0,48,100,33.0,48.8,66.3,53.6,...,13.3,10.0,18.2,24.8,11.1,19.4,25.6,46.6,56.9,66.6
1880,10019,US,2015-10-30T00:00:00-04:00,0,1,11,30.5,33.1,38.4,43.0,...,10.1,9.7,15.4,19.8,9.5,15.8,21.0,40.3,44.6,49.0
1881,10019,US,2015-10-31T00:00:00-04:00,0,17,51,30.9,35.6,43.7,37.0,...,5.9,1.4,6.8,13.7,1.4,7.0,13.9,36.5,42.8,47.6

In [68]:
#truncate data and rename labels
weather_truncate = weather_df[['timestamp','tempAvg','relHumAvg','snowDepth','windSpdAvg','precip']]
weather = weather_truncate.rename(columns={"timestamp": "Day",
                            "tempAvg": "Temperature (F)",
                            "relHumAvg": "Humitdity (%)",
                            "snowDepth": "Snowfall Depth (in)",
                            "windSpdAvg": "Wind Speed (MPH)",
                            "precip": "Precipitation (in)"})
weather

,Day,Temperature (F),Humitdity (%),Snowfall Depth (in),Wind Speed (MPH),Precipitation (in)
0,2020-02-29T00:00:00-05:00,30.2,44.1,0,11.0,0.00
1,2020-03-01T00:00:00-05:00,34.1,47.2,0,7.3,0.00
2,2020-03-02T00:00:00-05:00,47.8,56.0,0,6.7,0.00
3,2020-03-03T00:00:00-05:00,52.0,79.9,0,6.2,0.23
4,2020-03-04T00:00:00-05:00,49.9,50.3,0,12.4,0.00
...,...,...,...,...,...,...
1877,2015-10-27T00:00:00-04:00,50.6,68.6,0,4.0,0.00
1878,2015-10-28T00:00:00-04:00,59.5,91.3,0,11.0,1.19
1879,2015-10-29T00:00:00-04:00,64.1,62.0,0,9.1,0.05
1880,2015-10-30T00:00:00-04:00,52.5,47.6,0,7.4,0.00
1881,2015-10-31T00:00:00-04:00,48.2,62.2,0,3.6,0.00

In [101]:
#change days to month by slicing off datetime stopping on month
weather_month = weather
weather_month['Day'] = weather_month['Day'].str.slice(start=0,stop=7)
weather_month = weather_month.rename(columns={'Day':'Month'})
weather_month

,Month,Temperature (F),Humitdity (%),Snowfall Depth (in),Wind Speed (MPH),Precipitation (in)
0,2020-02,30.2,44.1,0,11.0,0.00
1,2020-03,34.1,47.2,0,7.3,0.00
2,2020-03,47.8,56.0,0,6.7,0.00
3,2020-03,52.0,79.9,0,6.2,0.23
4,2020-03,49.9,50.3,0,12.4,0.00
...,...,...,...,...,...,...
1877,2015-10,50.6,68.6,0,4.0,0.00
1878,2015-10,59.5,91.3,0,11.0,1.19
1879,2015-10,64.1,62.0,0,9.1,0.05
1880,2015-10,52.5,47.6,0,7.4,0.00
1881,2015-10,48.2,62.2,0,3.6,0.00

In [103]:
weather_month.to_csv('weather_by_month.csv')