In [3]:
import json
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
from configweather import api_key

In [4]:
#10021=new york new york, 10004= manhattan, 11212=brooklyn

postal_code = "10019"
country = "US"
period = "day"
timestamp_between = "2015-01-1T08:00-07:00,2015-12-30T23:00-07:00"

url = f"https://api.weathersource.com/v1/{api_key}/postal_codes/{postal_code},{country}/history.json?period={period}&timestamp_between={timestamp_between}"

weather_data = requests.get(url).json()
#print(json.dumps(weather_data, indent=4, sort_keys=True))

In [5]:
#loop through the first 10 days of the month
#index_loop = [1,2,3,4,5,6,7,8,9,10]
weather_df = pd.DataFrame(weather_data)

In [6]:
weather_df.to_csv('weather_data.csv')

In [7]:
weather_df.head()

,postal_code,country,timestamp,cldCvrMin,cldCvrAvg,cldCvrMax,dewPtMin,dewPtAvg,dewPtMax,feelsLikeMin,...,windSpdMax,windSpd80mMin,windSpd80mAvg,windSpd80mMax,windSpd100mMin,windSpd100mAvg,windSpd100mMax,wetBulbMin,wetBulbAvg,wetBulbMax
0,10019,US,2015-01-01T00:00:00-05:00,0,1,8,8.1,12.7,19.5,17.9,...,10.4,12.0,17.2,22.4,12.4,17.6,22.8,21.0,26.9,31.8
1,10019,US,2015-01-02T00:00:00-05:00,0,40,100,18.5,19.5,22.1,28.8,...,10.3,9.2,15.5,20.3,9.8,16.1,20.9,29.4,31.6,35.0
2,10019,US,2015-01-03T00:00:00-05:00,13,82,100,20.6,28.8,38.7,26.4,...,6.6,6.6,11.3,14.7,6.9,11.8,15.5,27.6,32.8,39.1
3,10019,US,2015-01-04T00:00:00-05:00,65,95,100,32.0,45.2,52.3,38.2,...,15.3,3.1,15.2,30.5,3.5,16.3,31.7,39.1,46.3,53.1
4,10019,US,2015-01-05T00:00:00-05:00,0,21,87,1.1,13.7,30.0,11.1,...,13.3,13.3,21.2,27.2,13.7,21.7,28.7,17.7,29.1,40.2

In [8]:
weather_df.columns

Index(['postal_code', 'country', 'timestamp', 'cldCvrMin', 'cldCvrAvg',
       'cldCvrMax', 'dewPtMin', 'dewPtAvg', 'dewPtMax', 'feelsLikeMin',
       'feelsLikeAvg', 'feelsLikeMax', 'heatIndexMin', 'heatIndexAvg',
       'heatIndexMax', 'mslPresMin', 'mslPresAvg', 'mslPresMax', 'precip',
       'presTendMin', 'presTendAvg', 'presTendMax', 'radSolarMin',
       'radSolarAvg', 'radSolarMax', 'radSolarTot', 'relHumMin', 'relHumAvg',
       'relHumMax', 'sfcPresMin', 'sfcPresAvg', 'sfcPresMax', 'snowDepth',
       'snowfall', 'spcHumMin', 'spcHumAvg', 'spcHumMax', 'tempMin', 'tempAvg',
       'tempMax', 'windChillMin', 'windChillAvg', 'windChillMax', 'windDirAvg',
       'windDir80mAvg', 'windDir100mAvg', 'windSpdMin', 'windSpdAvg',
       'windSpdMax', 'windSpd80mMin', 'windSpd80mAvg', 'windSpd80mMax',
       'windSpd100mMin', 'windSpd100mAvg', 'windSpd100mMax', 'wetBulbMin',
       'wetBulbAvg', 'wetBulbMax'],
      dtype='object')

In [10]:
weather_df = weather_df.rename(columns={"timestamp": "Day",
                            "tempAvg": "Temperature (F)",
                            "relHumAvg": "Humitdity (%)", 
                            "snowDepth": "Snowfall Depth (in)", 
                            "windSpdAvg": "Wind Speed (MPH)",
                            "precip": "Precipitation (in)"})

In [11]:
weather_df = weather_df[["Day", "Temperature (F)", "Humitdity (%)", "Snowfall Depth (in)", "Wind Speed (MPH)", "Precipitation (in)"]]
weather_df

,Day,Temperature (F),Humitdity (%),Snowfall Depth (in),Wind Speed (MPH),Precipitation (in)
0,2015-01-01T00:00:00-05:00,31.5,46.1,0.0,6.5,0.00
1,2015-01-02T00:00:00-05:00,36.6,49.7,0.0,5.7,0.00
2,2015-01-03T00:00:00-05:00,34.7,80.2,0.8,4.3,0.61
3,2015-01-04T00:00:00-05:00,47.4,93.0,0.2,5.9,0.26
4,2015-01-05T00:00:00-05:00,34.0,43.7,0.0,10.4,0.00
...,...,...,...,...,...,...
360,2015-12-27T00:00:00-05:00,51.8,92.5,0.0,6.8,0.02
361,2015-12-28T00:00:00-05:00,38.3,65.1,0.6,8.3,0.03
362,2015-12-29T00:00:00-05:00,38.8,97.0,0.9,6.7,0.44
363,2015-12-30T00:00:00-05:00,42.3,96.1,0.0,3.7,0.17
364,2015-12-31T00:00:00-05:00,44.5,79.7,0.0,5.9,0.02

In [12]:
#run average for month
#weather_df = weather_df['Day'].resample('M')
pd.to_datetime(weather_df["Day"])
weather_df

,Day,Temperature (F),Humitdity (%),Snowfall Depth (in),Wind Speed (MPH),Precipitation (in)
0,2015-01-01T00:00:00-05:00,31.5,46.1,0.0,6.5,0.00
1,2015-01-02T00:00:00-05:00,36.6,49.7,0.0,5.7,0.00
2,2015-01-03T00:00:00-05:00,34.7,80.2,0.8,4.3,0.61
3,2015-01-04T00:00:00-05:00,47.4,93.0,0.2,5.9,0.26
4,2015-01-05T00:00:00-05:00,34.0,43.7,0.0,10.4,0.00
...,...,...,...,...,...,...
360,2015-12-27T00:00:00-05:00,51.8,92.5,0.0,6.8,0.02
361,2015-12-28T00:00:00-05:00,38.3,65.1,0.6,8.3,0.03
362,2015-12-29T00:00:00-05:00,38.8,97.0,0.9,6.7,0.44
363,2015-12-30T00:00:00-05:00,42.3,96.1,0.0,3.7,0.17
364,2015-12-31T00:00:00-05:00,44.5,79.7,0.0,5.9,0.02

In [13]:
#run average of year
weather_df = weather_df[["Day", "Temperature (F)", "Humitdity (%)", "Snowfall Depth (in)", "Wind Speed (MPH)", "Precipitation (in)"]].mean()

In [14]:
weather_df = pd.DataFrame(weather_df)

In [15]:
weather_df

                             0
Temperature (F)      55.371233
Humitdity (%)        64.598082
Snowfall Depth (in)   1.210411
Wind Speed (MPH)      5.680274
Precipitation (in)    0.088630